language: java
env:
 - GALAXY_TEST_DEFAULT_INTERACTOR=api
before_install:
 - mkdir "$HOME/.python-eggs"
 - chmod 700 "$HOME/.python-eggs" 
 - cd ${TRAVIS_BUILD_DIR}
 - wget https://codeload.github.com/jmchilton/galaxy-central/tar.gz/master
 - tar -zxvf master | tail
 - cd galaxy-central-master
 - sudo apt-get install python-pip
   #- sudo pip install -U numpy
   # - sudo pip install -U scipy
 - sudo apt-get install -qq python-numpy python-scipy
 - sudo pip install -U pyyaml
 - sudo pip install -U matplotlib
 - sudo pip install -U scikit-learn
 - sudo pip install -U fastcluster
 - sudo pip install -U http://openscreen.cz/software/inchlib/static/inchlib_clust/inchlib_clust-0.1.3.zip
 - sudo pip install -U requests
 - sudo pip install -U xlrd
 - sudo pip install -U beautifulsoup4
 - sudo pip install -U pycurl
 - sudo pip install -U pyvcf

install:
 - export GALAXY_TEST_UPLOAD_ASYNC=false
 - export GALAXY_TEST_VERBOSE_ERRORS=True 
 - export GALAXY_TEST_DB_TEMPLATE=https://github.com/jmchilton/galaxy-downloads/raw/master/db_gx_rev_0120.sqlite
 - export GALAXY_TEST_TOOL_CONF=${TRAVIS_BUILD_DIR}/.travis.tool_conf.xml
 - echo $GALAXY_TEST_TOOL_CONF
 - ln -s ${TRAVIS_BUILD_DIR}/chasm_webservice tools/chasm_webservice
 - ln -s ${TRAVIS_BUILD_DIR}/condel_web tools/condel_web
 - ln -s ${TRAVIS_BUILD_DIR}/replace_delimiter tools/replace_delimiter
 - ln -s ${TRAVIS_BUILD_DIR}/driver_to_inchlib tools/driver_to_inchlib
 - ln -s ${TRAVIS_BUILD_DIR}/inchlib_clust tools/inchlib_clust
 - ln -s ${TRAVIS_BUILD_DIR}/fathmm tools/fathmm
 - ln -s ${TRAVIS_BUILD_DIR}/merge_columns_with_delimiter tools/merge_columns_with_delimiter
 - ln -s ${TRAVIS_BUILD_DIR}/mutationassesor_web tools/mutationassesor_web
 - ln -s ${TRAVIS_BUILD_DIR}/polyphen2_web tools/polyphen2_web
 - ln -s ${TRAVIS_BUILD_DIR}/sift_web tools/sift_web
 - ln -s ${TRAVIS_BUILD_DIR}/transFIC_web tools/transFIC_web
 - ln -s ${TRAVIS_BUILD_DIR}/vep_rest tools/vep_rest
 - cp ${TRAVIS_BUILD_DIR}/test-data/* test-data/
 - ./run.sh --stop-daemon || true

script:
 - python ./scripts/functional_tests.py -v `python tool_list.py Driver-Mutation-Tools`

